services:
    local-db:
        image: mysql:8.0
        container_name: local-db
        ports:
            - ${MYSQL_OUTER_PORT}:${MYSQL_INNER_PORT}
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: bears-local-db
        volumes:
          - ./mysql:/var/lib/mysql
    adminer_container:
      image: adminer:latest
      environment:
        ADMINER_DEFAULT_SERVER: local-db
      ports:
        - ${DB_VIEWER_OUTER_PORT}:${DB_VIEWER_INNER_PORT}