import { Role } from '@prisma/client';

export const userProfiles = [
  {
    email: 'bob@email.com',
    password: 'BobPass1!',
    role: Role.STUDENT,
    profile: {
      firstName: 'Bob',
      lastName: 'Bobby',
      age: 18,
      bio: 'Looking to learn',
      subjects: 'Math, English',
      edLevel: 'Secondary',
      phone: '360-295-2685',
      city: 'Olympia',
      state: 'WA',
    },
  },
  {
    email: 'guy@email.com',
    password: 'GuyPass1!',
    role: Role.STUDENT,
    profile: {
      firstName: 'Guy',
      lastName: 'Mann',
      age: 22,
      bio: 'Need help with educations',
      subjects: 'English',
      edLevel: 'College',
      phone: '360-295-2685',
      city: 'Olympia',
      state: 'WA',
    },
  },
  {
    email: 'aaron@email.com',
    password: 'AaronPass1!',
    role: Role.TUTOR,
    profile: {
      firstName: 'Aaron',
      lastName: 'Smoothie',
      age: 50,
      bio: 'I am a tutor',
      subjects: 'Math, English, Biology',
      edLevel: 'Secondary',
      phone: '360-295-2685',
      city: 'Olympia',
      state: 'WA',
      rate: 20.55,
    },
  },
  {
    email: 'ron@email.com',
    password: 'RonPass1!',
    role: Role.TUTOR,
    profile: {
      firstName: 'Ron',
      lastName: 'Person',
      age: 29,
      bio: 'I am a person that teaches',
      subjects: 'Computer Science',
      edLevel: 'College',
      phone: '360-295-2685',
      city: 'Olympia',
      state: 'WA',
      rate: 60.25,
    },
  },
  {
    email: 'perry@email.com',
    password: 'SomePass1!',
    role: Role.TUTOR,
    profile: {
      firstName: 'Perry',
      lastName: 'Plat',
      age: 32,
      bio: 'Just teaching things',
      subjects: 'Math, Chemistry',
      edLevel: 'Secondary',
      phone: '360-295-2685',
      city: 'Olympia',
      state: 'WA',
      rate: 12.65,
    },
  },
  {
    email: 'Shar@email.com',
    password: 'Password1!',
    role: Role.TUTOR,
    profile: {
      firstName: 'Shar',
      lastName: 'Mio',
      age: 18,
      bio: 'Looking to learn',
      subjects: 'Math, English',
      edLevel: 'Secondary',
      phone: '360-295-2685',
      city: 'Olympia',
      rate: 50.65,
      state: 'WA',
    },
  },
  {
    email: 'hank@email.com',
    password: 'HankPass1!',
    role: Role.TUTOR,
    profile: {
      firstName: 'Hank',
      lastName: 'Smith',
      age: 42,
      bio: 'Teaching all science subjects',
      subjects: 'Physics, Biology, Chemistry',
      edLevel: 'College',
      phone: '360-295-2685',
      city: 'Seattle',
      rate: 70.25,
      state: 'WA',
    },
  },
  {
    email: 'Lori@email.com',
    password: 'Password123!',
    role: Role.TUTOR,
    profile: {
      firstName: 'Lori',
      lastName: 'Smith',
      age: 35,
      bio: 'Teaching is so much fun!',
      subjects: 'Math, Biology, English',
      edLevel: 'Primary',
      phone: '360-295-2685',
      city: 'Seattle',
      rate: 55.55,
      state: 'WA',
    },
  },
  {
    email: 'Larry@email.com',
    password: 'Password123!',
    role: Role.TUTOR,
    profile: {
      firstName: 'Larry',
      lastName: 'Hun',
      age: 21,
      bio: 'Subjects made easy',
      subjects: 'Computer Science, Math',
      edLevel: 'College',
      phone: '360-295-2685',
      city: 'Vancouver',
      rate: 10.23,
      state: 'WA',
    },
  },
  {
    email: 'Godfrey@email.com',
    password: 'Password123!',
    role: Role.TUTOR,
    profile: {
      firstName: 'Godfrey',
      lastName: 'James',
      age: 66,
      bio: 'Teaching sciences',
      subjects: 'Chemistry, Biology, Physics',
      edLevel: 'College',
      phone: '360-295-2685',
      city: 'Portland',
      rate: 20.55,
      state: 'OR',
    },
  },
  {
    email: 'marla@email.com',
    password: 'Password123!',
    role: Role.TUTOR,
    profile: {
      firstName: 'Marla',
      lastName: 'Green',
      age: 21,
      bio: 'Love Teaching',
      subjects: 'Math, English, Physics',
      edLevel: 'Secondary',
      phone: '360-295-2685',
      city: 'Portland',
      rate: 10.23,
      state: 'OR',
    },
  },
  {
    email: 'Tai@email.com',
    password: 'Password123!',
    role: Role.TUTOR,
    profile: {
      firstName: 'Tai',
      lastName: 'Boo',
      age: 51,
      bio: 'This is my bio',
      subjects: 'Computer Science, Math',
      edLevel: 'Primary',
      phone: '360-295-2685',
      city: 'Salem',
      rate: 60.66,
      state: 'OR',
    },
  },
  {
    email: 'Dar@email.com',
    password: 'Password123!',
    role: Role.TUTOR,
    profile: {
      firstName: 'Dar',
      lastName: 'Lem',
      age: 31,
      bio: 'Subjects made easy',
      subjects: 'Computer Science, Math, Chemistry, Physics',
      edLevel: 'Primary',
      phone: '360-295-2685',
      city: 'Salem',
      rate: 42.23,
      state: 'OR',
    },
  },
  {
    email: 'Teach@email.com',
    password: 'Password123!',
    role: Role.TUTOR,
    profile: {
      firstName: 'Teach',
      lastName: 'Er',
      age: 21,
      bio: 'Teaching things and stuff',
      subjects: 'Computer Science, English, Biology',
      edLevel: 'College',
      phone: '360-295-2685',
      city: 'Los Angeles',
      rate: 90.63,
      state: 'CA',
    },
  },
  {
    email: 'Carlb@email.com',
    password: 'Password123!',
    role: Role.STUDENT,
    profile: {
      firstName: 'Carl',
      lastName: 'Belo',
      age: 16,
      bio: 'Need helps with computer science',
      subjects: 'Computer Science',
      edLevel: 'College',
      phone: '360-295-2685',
      city: 'Los Angeles',
      state: 'CA',
    },
  },
  {
    email: 'test@email.com',
    password: 'Password123!',
    role: Role.STUDENT,
    profile: {
      firstName: 'Test',
      lastName: 'Testing',
      age: 50,
      bio: 'Math is hard',
      subjects: 'Math',
      edLevel: 'Primary',
      phone: '360-295-2685',
      city: 'Seattle',
      state: 'WA',
    },
  },
  {
    email: 'me@gmail.com',
    password: 'Password123!',
    role: Role.STUDENT,
    profile: {
      firstName: 'Me',
      lastName: 'Ma',
      age: 25,
      bio: 'English!!!!',
      subjects: 'English',
      edLevel: 'Secondary',
      phone: '360-295-2685',
      city: 'Salem',
      state: 'OR',
    },
  },
  {
    email: 'ronald@email.com',
    password: 'Password123!',
    role: Role.STUDENT,
    profile: {
      firstName: 'Ronald',
      lastName: 'Duddley',
      age: 72,
      bio: 'Always learning',
      subjects: 'Chemistry, English',
      edLevel: 'College',
      phone: '360-295-2685',
      city: 'Olympia',
      state: 'WA',
    },
  },
  {
    email: 'wa@email.com',
    password: 'Password123!',
    role: Role.STUDENT,
    profile: {
      firstName: 'WA',
      lastName: 'WA',
      age: 10,
      bio: 'Yes, hello, help, thanks',
      subjects: 'Math, English, Chemistry, Computer Science, Physics',
      edLevel: 'Secondary',
      phone: '360-295-2685',
      city: 'Olympia',
      state: 'WA',
    },
  },
];
